{% set version = '2.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shinysky
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/mingwandroid/ShinySky/archive/{{ version }}.tar.gz
  sha256: 0d61c5f5bd9778111f0cfd5882b667dbab3e6e19c239969a4ea450f4b40aaeb9

build:
  noarch: generic
  number: 1005
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rjsonio
    - r-plyr
    - r-shiny
  run:
    - r-base
    - r-rjsonio
    - r-plyr
    - r-shiny

test:
  commands:
    - $R -e "library('shinysky')"  # [not win]
    - "\"%R%\" -e \"library('shinysky')\""  # [win]

about:
  home: https://github.com/mingwandroid/ShinySky
  license: MIT
  license_family: MIT
  summary: A set of Shiny UI components includings alerts and styled buttons
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
