appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fxc8EFrLZFLJ8rkbidduQvoSTOeUUDt8YQrYEfmnGsiPSFkfFTA/vE3f65/W2P8Q52/IVMU8I+IRFWC1aE9w4WJjljTXp1EzqNIj7kF3wSZoLAuA24Rb6i7ifKYTUmG2HbENyB+ad/RmYFa1PSmgm8fODrwcDt4HoVzRrpidNqayFrc1PKwoi77c9nrCbU59+BqTWZAPYQCQNTMqsoZdgTVZnJL6Dt0RTAa1jBj+RyyI5HH4SAiJln3f1xFcbKvAAvrHUeOSsL53pQjcEtXO5slDGDKZrmmpXOck7xrHuZXjsMgoNmTsa4kQm6TCWGzh+QFwNdqA2N2hzRoUt1mNltghSo+O+A1HTdsbUw7fbJvEyARNl8jzej1xk6itiakLQnXB2FRmt76Mx2Iy8A3Qkl65EFtQMfnGRU5Zae+mu4yrfseqrmXQxko0Ogxka88jD9jM5/OiRs2n1RALrb3thSUn0TJcqjeKxuDbuegErRmlnNkhE85rHg72Xe1AU1Piw10M3GOCVoAcB5uLw9Gnp/wlZ4h2CfWRvS0oDKlso/oXNwTgBORLwmdAbboPMx0ev11UIS5lvZGtWdGp12vNdVyOSM5ZXEtLBF72IABmnNXbJ2r1z59bNjKbwHOghSUH6aPZwdbr1KSg8WIGh08hl7h5fFuSkwJdXC3838SCgis=
